apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-src
    type: front-end
spec:
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
   spec:
     containers:
       - name: nginx-web
         image: nginx
         ports:
          - containerPort: 80
  replicas: 3
