apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
  labels:
    name: nginx-srv
spec:
  ports:
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
